<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzd7lwt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzd7lwt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVzd7lwt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVzd7lwt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVzd7lwt\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vzd7lwt',
    'container.build_id' => 'c4fe8f3d',
    'container.build_time' => 1542863975,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzd7lwt');
